USE DB_DWH;

EXEC STG.RUN_TRAFFIC_ACCIDENTS 
    @DEFAULT = 1;

EXEC STG.RUN_TRAFFIC_ACCIDENTS_PARTICIPATION_CAUSE 
    @DEFAULT = 1;

EXEC STG.RUN_TRAFFIC_ACCIDENTS_PARTICIPATION_CATEGORY_LOCATION_POF
    @DEFAULT = 1;

EXEC STG.RUN_TRAFFIC_ACCIDENTS_PARTICIPATION_CATEGORY_LOCATION_PARTICIPANTS
    @DEFAULT = 1;