table CORE_FACT_TRAFFIC_ACCIDENTS_PARTICIPATION_CATEGORY_LOCATION_PARTICIPANTS
	lineageTag: 4bc85a20-4df6-4004-9915-5d66c50acdf0

	measure 'Particpants overall' = SUM(CORE_FACT_TRAFFIC_ACCIDENTS_PARTICIPATION_CATEGORY_LOCATION_PARTICIPANTS[PARTICIPANTS])
		formatString: 0
		lineageTag: 1175efae-d12c-4399-a609-e082f86b61f9

	column FACT_ID
		dataType: int64
		formatString: 0
		lineageTag: 3b4bbf70-b2d0-42e0-8bd6-d1babe377d05
		summarizeBy: count
		sourceColumn: FACT_ID

		annotation SummarizationSetBy = Automatic

	column AGE_ID
		dataType: int64
		formatString: 0
		lineageTag: efff12cc-7b35-4e77-8619-8d987c4ca827
		summarizeBy: none
		sourceColumn: AGE_ID

		annotation SummarizationSetBy = Automatic

	column ROAD_ENVIRONMENT_ID
		dataType: int64
		formatString: 0
		lineageTag: af8f8f6a-9531-4a62-bd21-b7c7a4e5fbdc
		summarizeBy: none
		sourceColumn: ROAD_ENVIRONMENT_ID

		annotation SummarizationSetBy = Automatic

	column TRAFFIC_PARTICIPATION_ID
		dataType: int64
		formatString: 0
		lineageTag: 0aff1466-6ada-4579-80e6-673cd235caa5
		summarizeBy: none
		sourceColumn: TRAFFIC_PARTICIPATION_ID

		annotation SummarizationSetBy = Automatic

	column SEX_ID
		dataType: int64
		formatString: 0
		lineageTag: cdbbf6d3-5155-4ccc-ac47-4f3297f61158
		summarizeBy: none
		sourceColumn: SEX_ID

		annotation SummarizationSetBy = Automatic

	column TRAFFIC_ACCIDENT_CATEGORY_ID
		dataType: int64
		formatString: 0
		lineageTag: 9a7abb96-2b50-439d-b0cc-5f625ba981e4
		summarizeBy: none
		sourceColumn: TRAFFIC_ACCIDENT_CATEGORY_ID

		annotation SummarizationSetBy = Automatic

	column YEAR
		dataType: int64
		formatString: 0
		lineageTag: 7e83cd4a-f03a-4035-8e17-712bcf4803a1
		summarizeBy: sum
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column MONTH
		dataType: int64
		formatString: 0
		lineageTag: e945bef1-e696-4c23-ac72-11a1b1467ae1
		summarizeBy: sum
		sourceColumn: MONTH

		annotation SummarizationSetBy = Automatic

	column PARTICIPANTS
		dataType: int64
		formatString: 0
		lineageTag: c2e0db7c-f06e-478a-a45d-5910ab88b014
		summarizeBy: sum
		sourceColumn: PARTICIPANTS

		annotation SummarizationSetBy = Automatic

	column STAMP_SOURCE
		dataType: string
		lineageTag: fd9aebc6-6bc6-4987-a03b-21932c79cf25
		summarizeBy: none
		sourceColumn: STAMP_SOURCE

		annotation SummarizationSetBy = Automatic

	column STAMP_SOURCE_STG
		dataType: string
		lineageTag: 48e37c2e-1bf2-45aa-854d-afe5a900f55d
		summarizeBy: none
		sourceColumn: STAMP_SOURCE_STG

		annotation SummarizationSetBy = Automatic

	column STAMP_TIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 2dcf3f96-324c-47b9-a018-6703a4c93e6a
		summarizeBy: none
		sourceColumn: STAMP_TIME

		variation Variation
			isDefault
			relationship: 52fc9bab-2ed1-4398-9811-f46f693a6080
			defaultHierarchy: LocalDateTable_ce370459-b285-44d3-929b-fb85ebe41e8a.Datumshierarchie

		annotation SummarizationSetBy = Automatic

	column STAMP_TIME_STG
		dataType: dateTime
		formatString: General Date
		lineageTag: 229b8182-a878-4caa-b6a9-175134a106ea
		summarizeBy: none
		sourceColumn: STAMP_TIME_STG

		variation Variation
			isDefault
			relationship: ef37c401-51b0-4779-be9d-0870e5834f8b
			defaultHierarchy: LocalDateTable_faba17e8-0f74-4052-84b1-668704ea8593.Datumshierarchie

		annotation SummarizationSetBy = Automatic

	column EOMONTH
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9aae49f5-9d6f-446f-855d-3138aedd9fe0
		summarizeBy: none
		sourceColumn: EOMONTH

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition CORE_FACT_TRAFFIC_ACCIDENTS_PARTICIPATION_CATEGORY_LOCATION_PARTICIPANTS = m
		mode: import
		source =
				let
				    Quelle = Sql.Databases(".\MSSQLSERVER01"),
				    DB_DWH = Quelle{[Name="DB_DWH"]}[Data],
				    CORE_FACT_TRAFFIC_ACCIDENTS_PARTICIPATION_CATEGORY_LOCATION_PARTICIPANTS = DB_DWH{[Schema="CORE",Item="FACT_TRAFFIC_ACCIDENTS_PARTICIPATION_CATEGORY_LOCATION_PARTICIPANTS"]}[Data],
				    #"Hinzugefügte benutzerdefinierte Spalte" = Table.AddColumn(CORE_FACT_TRAFFIC_ACCIDENTS_PARTICIPATION_CATEGORY_LOCATION_PARTICIPANTS, "EOMONTH", each Date.EndOfMonth(Date.From(#date([YEAR],[MONTH],1)))),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Hinzugefügte benutzerdefinierte Spalte",{{"EOMONTH", type date}})
				in
				    #"Geänderter Typ"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

